### PR TITLE
WIP - Separate DB from API

### PR DESCRIPTION
**Pull request by adamkerz**

### CODE REVIEW

**Comment by monkeypants** [comment]
@adamkerz 
```
#!/bin/bash python pie.py setup python pie.py build — Shell Script <1s
[2020-06-03T08:39:42.200Z] Task setup could not be found.
[2020-06-03T08:39:42.477Z] Task build could not be found.
script returned exit code 1
```

**Comment by adamkerz** [comment]
Think I just have to work around the `host.docker.internal` issue now...

**Comment by adamkerz** [comment]
Or not... But it doesn't work for Chris, so trying this magic IP address: 172.17.0.1

**Comment by monkeypants** [comment]
This seems to work well, is there a reason not to merge yet?

**Comment by adamkerz** [comment]
Needs more tidying up, but sufficient to merge now (once the last commit passes)

**Pull request merged**
