### PR TITLE
fix: create production manage py for aws deploys

### PR DESCRIPTION
**Pull request by roleyfoley**
manage.py uses the Development Config which overrides the base SQL lookup 

This creates a production manage.py which can be used for lambda and docker images in deployment

### CODE REVIEW

**Comment by adamkerz** [comment]
@magicjohnson I'm not seeing the value in the different Config classes? Looks to me like we can just have one config class that has some conditionals to handle things like KMS or not. Ie. the only difference between different environments (including a test environment) is the environment variables. Can you explain to me what benefit we get from having different config classes?

**Comment by magicjohnson** [comment]
This config management solution is based on Flask "best practices", although I don't really like it because e.g Production config code is executed even when you run app with Testing (since all settings are in class definition). I don't like conditionals in configuration as well and prefer something like django's users do - having different config modules.

**Comment by koriaf** [comment]
could be a task for far future (which never be handled because we have many other things to do here - like secret keys support) - either split these classes to submodules or merge them relying on env variables more.

**Comment by adamkerz** [comment]
I just meant conditionals for KMS and things like that, not conditionals for different environments. Ie. "if you give me a KMS value, I decrypt it, otherwise I don't". Not "if this is prod, I decrypt KMS, otherwise I don't".

I think (hope) that we can usually just run the same code and config with different values in all environments.

**Pull request merged**
