### PR TITLE
Build and test fixes for CI

### PR DESCRIPTION
**Pull request by adamkerz**

### CODE REVIEW

**Comment by adamkerz** [comment]
@roleyfoley OK, I've updated the Jenkins file, but how do I tell Jenkins to use it for this PR? Will it do it if merged or only if we do some other steps?

**Comment by roleyfoley** [comment]
The pipeline uses the Jenkins file that it can find for that branch/PR so any changes you’ve added should be reflected in the job

**Comment by roleyfoley** [comment]
Fixed up looks like the actual test command was using docker-compose instead of pie.py so your changes were overriden

**Comment by adamkerz** [comment]
WTH... not sure how I managed to commit the other changes but not that one... Thank you!

**Pull request merged**
